### PR TITLE
Add option to give specific text position to "Say"

### PR DESCRIPTION
**Pull request by tzachshabtay**
This is the equivalent to "SayAt" in AGS, you can now override the text position by doing: "await cEgo.SayAsync("Hello!", (100, 50));"

You can also override the portrait position (if there's a configured portrait): "await cEgo.SayAsync("Hello!", portraitPosition: (100, 50));"

### CODE REVIEW

**Comment by ivan-mogilko** [comment]
I realize you are probably adding this to make it easier for newcomers, but imho this again assumes particular speech style and "portrait" entity in the engine API (something we discussed a while ago).
Idk what's your plan on this, but just wanted to note this.

**Comment by tzachshabtay** [comment]
I don't have any particular plans for it. I'm currently content with the compromise of having a built-in "portrait" entity in the API as I know this is very common in adventure games, and those games that don't need a portrait can simply ignore it.
I'm happy to discuss alternative APIs though that still allow for easy plug & play portraits, though, if you have any ideas.

Other than the portrait issue, my only assumption on speech style here that I can see is that there's text that needs to be displayed somewhere on the screen, and I don't see an issue with it?

**Comment by ivan-mogilko** [comment]
Yes, I realize this may be kind of too much abstraction in what I am talking about. I was wondering though if there could be some kind of "middle-level" solution to this. I.e., if we are importing a template library that implements a speech style, or group of speech styles based on displaying text w/wo portrait, then it may also provide additional scripting functions to deal with positioning.

The only thought that comes at the moment is this: if there were the way to get the "object" that displays speech on screen (not sure what it is at the moment), either as return value of Say, or in any other reliable way, then one could write an extension method, e.g. (pseudo code):

<pre>
void SayAt(this Character, string text, PointF textPositionl, PointF portraitPosition)
{
    Task task = this.Say(text);
    var sayLocation = ... get somehow.
    sayLocation.TextPosition = textPosition;
    sayLocation.PortraitPosition = portraitPosition;
    return task;
}
</pre>

**Comment by tzachshabtay** [comment]
There is a way to get that "object" using the "OnBeforeSay" event, so one could have written an extension method:

```cs

Action<BeforeSayEventArgs> setPosition = args => 
{
   args.Label.Position = textPosition;
   character.SpeechConfig.PortaitConfig.Portrait.Position = portraitPosition;
};
character.OnBeforeSay.Subscribe(setPosition);
await character.SayAsync("Hello");
character.OnBeforeSay.Unsubscribe(setPosition);

```

But this is not as pretty as built-in support, and also in case a character says several things at the same time where you want different positions it will get even uglier.

**Comment by ivan-mogilko** [comment]
Hmmm, no, this certainly does not look like a good thing...

**Pull request merged**
