### PR TITLE
Remove strict requirement for a specific dotnet core version

### PR DESCRIPTION
**Pull request by tzachshabtay**

### CODE REVIEW

**Comment by persn** [comment]
You probably already know but I think the Appveyor build is failing because the source code contains a project using Portable Class Libraries, which is phased out by Microsoft. It should be converted to the new .csproj standard

**Comment by tzachshabtay** [comment]
I knew they were phasing it out, but I didn't know that was the reason for the error (which is not really revealing). Thanks!
I'll convert the project to the new format, then.

**Comment by persn** [comment]
I don't know for sure, I'm just guessing from the error message.

**Comment by tzachshabtay** [comment]
It makes perfect sense, and I wanted to convert the project anyway eventually. 

Technically, it should work with PCLs as Microsoft wants to keep backwards compatibility with them as far as I know, but it's also the most likely candidate of something that they neglect to maintain with new changes.

**Comment by persn** [comment]
New errors, hooray. I'm able to reproduce them on my own computer by running `dotnet build`, not sure why it happens however.

**Comment by tzachshabtay** [comment]
I think this is why: https://bugzilla.xamarin.com/show_bug.cgi?id=58254
I'll try switching to msbuild restore.

Note, though, that dotnet core is not yet supported, only mono (which uses dotnet core tooling), so `dotnet build` is not the command to run, but `dotnet msbuild` (to my best understanding).

**Pull request merged**
